grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: dikshaturkar2022@gmail.com
      password: $__file{/etc/secrets/smtp_password}
      from_address: dikshaturkar2022@gmail.com
      from_name: Grafana Alerts
      skip_verify: true

  extraSecretMounts:
    - name: smtp-secret
      secretName: grafana-smtp-secret
      mountPath: /etc/secrets
      readOnly: true