grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: dikshaturkar2022@gmail.com
      password: lryptfnitxidxwze
      from_address: dikshaturkar2022@gmail.com
      from_name: Grafana Alerts
      skip_verify: true