name: Infra Provisioning Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/envs/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

     
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: Terraform-eks
        run: terraform destroy -auto-approve

      # 🔥 APPLY (default for push + manual apply)
      - name: Terraform Plan
        if: ${{ github.event.inputs.action != 'destroy' }}
        run: terraform plan -out=tfplan

     # - name: Terraform Apply
      #  if: ${{ github.event.inputs.action != 'destroy' }}
      #  run: terraform apply -auto-approve tfplan


  post-provision:
    runs-on: ubuntu-latest
    needs: terraform

    # 🔥 RUN for push + manual apply
    if: ${{ github.event.inputs.action != 'destroy' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name my-eks-cluster

      - name: Wait for cluster readiness
        run: |
          for i in {1..15}; do
            kubectl get nodes && break || sleep 20
          done

      - name: Install ArgoCD
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm upgrade --install argocd argo/argo-cd \
            -f helm/argocd-values.yaml \
            -n argocd --create-namespace

      - name: Install Prometheus & Grafana
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
            -f helm/prometheus-values.yaml \
            -n monitoring --create-namespace

      - name: Install NGINX Ingress
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            -n ingress --create-namespace

      - name: Verify Cluster Setup
        run: |
          kubectl get nodes -o wide
          kubectl get pods -A
          kubectl get svc -A

